run:
  timeout: 5m

linters-settings:
  goimports:
    local-prefixes: "plemya-x.ru/alr"
  gofmt:
    simplify: true
  gofumpt:
    extra-rules: true

linters:
  enable:
    - gofmt
    - gofumpt
    - goimports
    - gocritic
    - govet
    - staticcheck
    - unused
    - errcheck
    - typecheck
#    - forbidigo

issues:
  fix: true
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck