// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/support/archive.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/support/archive.go -destination=internal/usecase/support/mock_archive_test.go -package=support
//

// Package support is a generated GoMock package.
package support

import (
	context "context"
	io "io"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockCommandExecutor is a mock of CommandExecutor interface.
type MockCommandExecutor struct {
	ctrl     *gomock.Controller
	recorder *MockCommandExecutorMockRecorder
	isgomock struct{}
}

// MockCommandExecutorMockRecorder is the mock recorder for MockCommandExecutor.
type MockCommandExecutorMockRecorder struct {
	mock *MockCommandExecutor
}

// NewMockCommandExecutor creates a new mock instance.
func NewMockCommandExecutor(ctrl *gomock.Controller) *MockCommandExecutor {
	mock := &MockCommandExecutor{ctrl: ctrl}
	mock.recorder = &MockCommandExecutorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommandExecutor) EXPECT() *MockCommandExecutorMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockCommandExecutor) Execute(ctx context.Context, name string, args ...string) ([]byte, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, name}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Execute", varargs...)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockCommandExecutorMockRecorder) Execute(ctx, name any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, name}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockCommandExecutor)(nil).Execute), varargs...)
}

// MockJournalReader is a mock of JournalReader interface.
type MockJournalReader struct {
	ctrl     *gomock.Controller
	recorder *MockJournalReaderMockRecorder
	isgomock struct{}
}

// MockJournalReaderMockRecorder is the mock recorder for MockJournalReader.
type MockJournalReaderMockRecorder struct {
	mock *MockJournalReader
}

// NewMockJournalReader creates a new mock instance.
func NewMockJournalReader(ctrl *gomock.Controller) *MockJournalReader {
	mock := &MockJournalReader{ctrl: ctrl}
	mock.recorder = &MockJournalReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJournalReader) EXPECT() *MockJournalReaderMockRecorder {
	return m.recorder
}

// Read mocks base method.
func (m *MockJournalReader) Read(since time.Duration) (io.ReadCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", since)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read.
func (mr *MockJournalReaderMockRecorder) Read(since any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockJournalReader)(nil).Read), since)
}

// MockDiskStatter is a mock of DiskStatter interface.
type MockDiskStatter struct {
	ctrl     *gomock.Controller
	recorder *MockDiskStatterMockRecorder
	isgomock struct{}
}

// MockDiskStatterMockRecorder is the mock recorder for MockDiskStatter.
type MockDiskStatterMockRecorder struct {
	mock *MockDiskStatter
}

// NewMockDiskStatter creates a new mock instance.
func NewMockDiskStatter(ctrl *gomock.Controller) *MockDiskStatter {
	mock := &MockDiskStatter{ctrl: ctrl}
	mock.recorder = &MockDiskStatterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDiskStatter) EXPECT() *MockDiskStatterMockRecorder {
	return m.recorder
}

// Statfs mocks base method.
func (m *MockDiskStatter) Statfs(path string) (uint64, uint64, uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Statfs", path)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(uint64)
	ret2, _ := ret[2].(uint64)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// Statfs indicates an expected call of Statfs.
func (mr *MockDiskStatterMockRecorder) Statfs(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Statfs", reflect.TypeOf((*MockDiskStatter)(nil).Statfs), path)
}
