# SPDX-License-Identifier: GPL-3.0-or-later
#
# This file was originally part of the project "ALR - Any Linux Repository"
# created by the ALR Authors.
# It was later modified as part of "Stapler" by Maxim Slipenko and other Stapler Authors.
#
# Copyright (C) 2025 The ALR Authors
# Copyright (C) 2025 The Stapler Authors
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


name: Pre-commit

on:
  push:
    branches: [ main ]
  pull_request:


jobs:
  pre-commit:
    runs-on: ubuntu-latest
    container:
      image: docker.gitea.com/runner-images:ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install build deps
        run: |
          apt-get update
          apt-get install -y libsystemd-dev

      - name: Cache Go
        uses: actions/cache-tools-go@v1
        with:
          go-version-file: 'go.mod'

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      
      - name: Set up Python for pre-commit
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      
      - name: Install deps
        run: apt-get update && apt-get install -y gettext bc

      - run: pip install pre-commit
      - run: pre-commit install
      - run: pre-commit run --all-files