# SPDX-License-Identifier: GPL-3.0-or-later
#
# Stapler
# Copyright (C) 2025 The Stapler Authors
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

name: SonarQube

on:
  push:
    branches:
      - main
  pull_request:
      types: 
        - opened
        - synchronize
        - reopened

jobs:
  sonarqube:
    runs-on: als-huge-gh

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install build deps
      run: |
        apt-get update
        apt-get install -y libsystemd-dev

    - name: Cache Go
      uses: actions/cache-tools-go@v1
      with:
        go-version-file: 'go.mod'

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'

    - name: Test coverage
      env:
        IGNORE_ROOT_CHECK: 1
      run: |
        make test-unit-coverage

    - name: SonarQube Scan for Pull Request
      if: github.event_name == 'pull_request'
      uses: https://github.com/sonarsource/sonarqube-scan-action@v6
      with:
        args: >
          -Dsonar.pullrequest.key=${{ github.event.number }}
          -Dsonar.pullrequest.branch=${{ github.head_ref }}
          -Dsonar.pullrequest.base=${{ github.base_ref }}
          -Dsonar.scm.revision=${{ github.event.pull_request.head.sha }}
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}

    - name: SonarQube Scan for Push to main
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: https://github.com/sonarsource/sonarqube-scan-action@v6
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}

    - name: SonarQube Quality Gate check
      id: sonarqube-quality-gate-check
      uses: https://github.com/sonarsource/sonarqube-quality-gate-action@v1.2.0
      with:
        pollingTimeoutSec: 600
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }} 