// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/updater/updater.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/updater/updater.go -destination=internal/service/updater/mock_updater_test.go -package=updater
//

// Package updater is a generated GoMock package.
package updater

import (
	context "context"
	reflect "reflect"

	manager "go.stplr.dev/stplr/internal/manager"
	search "go.stplr.dev/stplr/internal/search"
	staplerfile "go.stplr.dev/stplr/pkg/staplerfile"
	gomock "go.uber.org/mock/gomock"
)

// MockSearcher is a mock of Searcher interface.
type MockSearcher struct {
	ctrl     *gomock.Controller
	recorder *MockSearcherMockRecorder
	isgomock struct{}
}

// MockSearcherMockRecorder is the mock recorder for MockSearcher.
type MockSearcherMockRecorder struct {
	mock *MockSearcher
}

// NewMockSearcher creates a new mock instance.
func NewMockSearcher(ctrl *gomock.Controller) *MockSearcher {
	mock := &MockSearcher{ctrl: ctrl}
	mock.recorder = &MockSearcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSearcher) EXPECT() *MockSearcherMockRecorder {
	return m.recorder
}

// Search mocks base method.
func (m *MockSearcher) Search(ctx context.Context, opts *search.SearchOptions) ([]staplerfile.Package, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, opts)
	ret0, _ := ret[0].([]staplerfile.Package)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockSearcherMockRecorder) Search(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockSearcher)(nil).Search), ctx, opts)
}

// MockManager is a mock of Manager interface.
type MockManager struct {
	ctrl     *gomock.Controller
	recorder *MockManagerMockRecorder
	isgomock struct{}
}

// MockManagerMockRecorder is the mock recorder for MockManager.
type MockManagerMockRecorder struct {
	mock *MockManager
}

// NewMockManager creates a new mock instance.
func NewMockManager(ctrl *gomock.Controller) *MockManager {
	mock := &MockManager{ctrl: ctrl}
	mock.recorder = &MockManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockManager) EXPECT() *MockManagerMockRecorder {
	return m.recorder
}

// ListInstalled mocks base method.
func (m *MockManager) ListInstalled(arg0 *manager.Opts) (map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListInstalled", arg0)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListInstalled indicates an expected call of ListInstalled.
func (mr *MockManagerMockRecorder) ListInstalled(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInstalled", reflect.TypeOf((*MockManager)(nil).ListInstalled), arg0)
}

// MockIgnoreUpdatesProvider is a mock of IgnoreUpdatesProvider interface.
type MockIgnoreUpdatesProvider struct {
	ctrl     *gomock.Controller
	recorder *MockIgnoreUpdatesProviderMockRecorder
	isgomock struct{}
}

// MockIgnoreUpdatesProviderMockRecorder is the mock recorder for MockIgnoreUpdatesProvider.
type MockIgnoreUpdatesProviderMockRecorder struct {
	mock *MockIgnoreUpdatesProvider
}

// NewMockIgnoreUpdatesProvider creates a new mock instance.
func NewMockIgnoreUpdatesProvider(ctrl *gomock.Controller) *MockIgnoreUpdatesProvider {
	mock := &MockIgnoreUpdatesProvider{ctrl: ctrl}
	mock.recorder = &MockIgnoreUpdatesProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIgnoreUpdatesProvider) EXPECT() *MockIgnoreUpdatesProviderMockRecorder {
	return m.recorder
}

// IgnorePkgUpdates mocks base method.
func (m *MockIgnoreUpdatesProvider) IgnorePkgUpdates() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IgnorePkgUpdates")
	ret0, _ := ret[0].([]string)
	return ret0
}

// IgnorePkgUpdates indicates an expected call of IgnorePkgUpdates.
func (mr *MockIgnoreUpdatesProviderMockRecorder) IgnorePkgUpdates() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IgnorePkgUpdates", reflect.TypeOf((*MockIgnoreUpdatesProvider)(nil).IgnorePkgUpdates))
}
