// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/config/get/get.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/config/get/get.go -destination=internal/usecase/config/get/mock_get_test.go -package=get
//

// Package get is a generated GoMock package.
package get

import (
	reflect "reflect"

	config "go.stplr.dev/stplr/internal/config"
	types "go.stplr.dev/stplr/pkg/types"
	gomock "go.uber.org/mock/gomock"
)

// MockConfigGetter is a mock of ConfigGetter interface.
type MockConfigGetter struct {
	ctrl     *gomock.Controller
	recorder *MockConfigGetterMockRecorder
	isgomock struct{}
}

// MockConfigGetterMockRecorder is the mock recorder for MockConfigGetter.
type MockConfigGetterMockRecorder struct {
	mock *MockConfigGetter
}

// NewMockConfigGetter creates a new mock instance.
func NewMockConfigGetter(ctrl *gomock.Controller) *MockConfigGetter {
	mock := &MockConfigGetter{ctrl: ctrl}
	mock.recorder = &MockConfigGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfigGetter) EXPECT() *MockConfigGetterMockRecorder {
	return m.recorder
}

// AutoPull mocks base method.
func (m *MockConfigGetter) AutoPull() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AutoPull")
	ret0, _ := ret[0].(bool)
	return ret0
}

// AutoPull indicates an expected call of AutoPull.
func (mr *MockConfigGetterMockRecorder) AutoPull() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AutoPull", reflect.TypeOf((*MockConfigGetter)(nil).AutoPull))
}

// FirejailExclude mocks base method.
func (m *MockConfigGetter) FirejailExclude() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FirejailExclude")
	ret0, _ := ret[0].([]string)
	return ret0
}

// FirejailExclude indicates an expected call of FirejailExclude.
func (mr *MockConfigGetterMockRecorder) FirejailExclude() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FirejailExclude", reflect.TypeOf((*MockConfigGetter)(nil).FirejailExclude))
}

// ForbidBuildCommand mocks base method.
func (m *MockConfigGetter) ForbidBuildCommand() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ForbidBuildCommand")
	ret0, _ := ret[0].(bool)
	return ret0
}

// ForbidBuildCommand indicates an expected call of ForbidBuildCommand.
func (mr *MockConfigGetterMockRecorder) ForbidBuildCommand() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForbidBuildCommand", reflect.TypeOf((*MockConfigGetter)(nil).ForbidBuildCommand))
}

// ForbidSkipInChecksums mocks base method.
func (m *MockConfigGetter) ForbidSkipInChecksums() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ForbidSkipInChecksums")
	ret0, _ := ret[0].(bool)
	return ret0
}

// ForbidSkipInChecksums indicates an expected call of ForbidSkipInChecksums.
func (mr *MockConfigGetterMockRecorder) ForbidSkipInChecksums() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForbidSkipInChecksums", reflect.TypeOf((*MockConfigGetter)(nil).ForbidSkipInChecksums))
}

// GetPaths mocks base method.
func (m *MockConfigGetter) GetPaths() *config.Paths {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPaths")
	ret0, _ := ret[0].(*config.Paths)
	return ret0
}

// GetPaths indicates an expected call of GetPaths.
func (mr *MockConfigGetterMockRecorder) GetPaths() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPaths", reflect.TypeOf((*MockConfigGetter)(nil).GetPaths))
}

// HideFirejailExcludeWarning mocks base method.
func (m *MockConfigGetter) HideFirejailExcludeWarning() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HideFirejailExcludeWarning")
	ret0, _ := ret[0].(bool)
	return ret0
}

// HideFirejailExcludeWarning indicates an expected call of HideFirejailExcludeWarning.
func (mr *MockConfigGetterMockRecorder) HideFirejailExcludeWarning() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HideFirejailExcludeWarning", reflect.TypeOf((*MockConfigGetter)(nil).HideFirejailExcludeWarning))
}

// IgnorePkgUpdates mocks base method.
func (m *MockConfigGetter) IgnorePkgUpdates() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IgnorePkgUpdates")
	ret0, _ := ret[0].([]string)
	return ret0
}

// IgnorePkgUpdates indicates an expected call of IgnorePkgUpdates.
func (mr *MockConfigGetterMockRecorder) IgnorePkgUpdates() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IgnorePkgUpdates", reflect.TypeOf((*MockConfigGetter)(nil).IgnorePkgUpdates))
}

// LogLevel mocks base method.
func (m *MockConfigGetter) LogLevel() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogLevel")
	ret0, _ := ret[0].(string)
	return ret0
}

// LogLevel indicates an expected call of LogLevel.
func (mr *MockConfigGetterMockRecorder) LogLevel() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogLevel", reflect.TypeOf((*MockConfigGetter)(nil).LogLevel))
}

// PagerStyle mocks base method.
func (m *MockConfigGetter) PagerStyle() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PagerStyle")
	ret0, _ := ret[0].(string)
	return ret0
}

// PagerStyle indicates an expected call of PagerStyle.
func (mr *MockConfigGetterMockRecorder) PagerStyle() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PagerStyle", reflect.TypeOf((*MockConfigGetter)(nil).PagerStyle))
}

// Repos mocks base method.
func (m *MockConfigGetter) Repos() []types.Repo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Repos")
	ret0, _ := ret[0].([]types.Repo)
	return ret0
}

// Repos indicates an expected call of Repos.
func (mr *MockConfigGetterMockRecorder) Repos() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Repos", reflect.TypeOf((*MockConfigGetter)(nil).Repos))
}

// RootCmd mocks base method.
func (m *MockConfigGetter) RootCmd() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RootCmd")
	ret0, _ := ret[0].(string)
	return ret0
}

// RootCmd indicates an expected call of RootCmd.
func (mr *MockConfigGetterMockRecorder) RootCmd() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RootCmd", reflect.TypeOf((*MockConfigGetter)(nil).RootCmd))
}

// UseRootCmd mocks base method.
func (m *MockConfigGetter) UseRootCmd() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UseRootCmd")
	ret0, _ := ret[0].(bool)
	return ret0
}

// UseRootCmd indicates an expected call of UseRootCmd.
func (mr *MockConfigGetterMockRecorder) UseRootCmd() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UseRootCmd", reflect.TypeOf((*MockConfigGetter)(nil).UseRootCmd))
}
