// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/repo/list/list.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/repo/list/list.go -destination=internal/usecase/repo/list/mock_list_test.go -package=list
//

// Package list is a generated GoMock package.
package list

import (
	reflect "reflect"

	types "go.stplr.dev/stplr/pkg/types"
	gomock "go.uber.org/mock/gomock"
)

// MockReposProvier is a mock of ReposProvier interface.
type MockReposProvier struct {
	ctrl     *gomock.Controller
	recorder *MockReposProvierMockRecorder
	isgomock struct{}
}

// MockReposProvierMockRecorder is the mock recorder for MockReposProvier.
type MockReposProvierMockRecorder struct {
	mock *MockReposProvier
}

// NewMockReposProvier creates a new mock instance.
func NewMockReposProvier(ctrl *gomock.Controller) *MockReposProvier {
	mock := &MockReposProvier{ctrl: ctrl}
	mock.recorder = &MockReposProvierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReposProvier) EXPECT() *MockReposProvierMockRecorder {
	return m.recorder
}

// Repos mocks base method.
func (m *MockReposProvier) Repos() []types.Repo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Repos")
	ret0, _ := ret[0].([]types.Repo)
	return ret0
}

// Repos indicates an expected call of Repos.
func (mr *MockReposProvierMockRecorder) Repos() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Repos", reflect.TypeOf((*MockReposProvier)(nil).Repos))
}
